name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Release - ${{ matrix.platform.release_for }}
    permissions: write-all
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        platform:
          - release_for: Linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bin: gold_k
            name: gold_k-linux-amd64
          - release_for: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: gold_k.exe
            name: gold_k-windows-amd64.exe

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform.target }}

      - name: Build
        run: |
          cargo install sqlx-cli --no-default-features --features sqlite
          mkdir ./data
          touch ./data/gold_k.sqlite
          cargo build --release --bin gold_k --target ${{ matrix.platform.target }}

      - name: Prepare assets
        shell: bash
        run: |
          cd target/${{ matrix.platform.target }}/release
          mv ${{ matrix.platform.bin }} ${{ matrix.platform.name }}

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            target/${{ matrix.platform.target }}/release/${{ matrix.platform.name }}
          draft: false
          prerelease: false